routes/web.php
<?php

use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HotelController;
use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\RoomController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth()->login(
//    \App\Models\User::find(1)
//);

Route::group(['middleware' => 'auth'], function (){
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::resource('schedules', ScheduleController::class);
    Route::resource('bookings', BookingController::class);
    Route::resource('activities', ActivitiesController::class);
    Route::post('/{activity}/buy',[ActivitiesController::class,'purchaseTicket'])->name('buy.tickets');
    Route::get('themepark/activites',[PageController::class,'activities'])->name('themepark.activities');
    Route::get('user/history',[PageController::class, 'getUserHistory'])->name('user.history');
    Route::get('set/{schedule}/{hotel}',[PageController::class,'setScheduleRoom'])->name('set.schedule');
    Route::post('guest/{schedule}/{room}',[BookingController::class, 'guestBooking'])->name('confirm.create');
    Route::delete('tickets/{ticket}/{booking}',[TicketController::class, 'destroy'])->name('tickets.destroy');
});

Route::get('/',[PageController::class,'index'])->name('home');
Route::get('/home',[PageController::class,'index'])->name('home');
Route::get('/about',[PageController::class,'about'])->name('about');
Route::get('/themepark/hotels',[PageController::class,'hotel'])->name('themepark.hotels');

app/Models/Schedule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;

class Schedule extends Model
{
    use HasFactory, SoftDeletes;
    protected $guarded = [];

    protected $dates = [
        'starting',
        'due',
    ];

    public function path(){
        return "/schedules/{$this->slug}" ;
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function Room(){
        return $this->belongsToMany(Room::class);
    }

    public function image(){
        $image = $this->image ? $this->image : 'avatar.png';
        return Storage::disk('schedule')->url($image);
    }

    public function booking(){
        return $this->hasMany(booking::class);
    }

}

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ScheduleCreateRequest;
use App\Http\Requests\ScheduleUpdateRequest;
use App\Models\Hotel;
use App\Models\Schedule;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class ScheduleController extends Controller
{
    use HasFactory;


    public function index()
    {
        $events = Schedule::latest()->get();
        return view('themepark.schedule.index',compact('events'));
    }


    public function create()
    {
        return view('themepark.schedule.create');
    }

    public function store(ScheduleCreateRequest $request)
    {

        $data = [
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'starting' => $request->starting,
            'due' => $request->due,
            'description' => $request->description,
        ];

        if ($request->has('image')) {
            $data['image'] = request('image')->store('/', 'schedule');
        }

        Schedule::create($data);

        return redirect()->route('schedules.index')
                         ->with('success','Schedule created successfully.');
    }

    public function show(Schedule $schedule)
    {
        $event = $schedule;
        $hotels = Hotel::latest()->paginate(15);
        return view('themepark.schedule.show',compact('hotels','event'));

    }

    public function edit(Schedule $schedule)
    {
        return view('themepark.schedule.edit',compact('schedule'));
    }


    public function update(ScheduleUpdateRequest $request, Schedule $schedule)
    {
        $data = $request->all();

        if ($request->has('image')) {
            $data['image'] = request('image')->store('/', 'schedule');
        }

        $schedule->update($data);

        return redirect()->route('schedules.index')
            ->with('success','Schedule updated successfully.');

    }


    public function destroy(Schedule $schedule)
    {
        $schedule->delete();

        return redirect()->route('schedules.index')
                ->with('success','Schedule deleted successfully.');
    }
}

resources/views/themepark/schedule/create.blade.php
@extends('layouts.app')

@section('content')
<div class="bg-gray-300">
    <div x-data="{ open: true }" x-show="open" class="fixed bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex  sm:items-center sm:justify-center">
                <div x-show="open" x-description="Background overlay, show/hide based on modal state."
                     x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" class="fixed inset-0 transition-opacity">
                    <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
                </div>

                <div x-show="open" x-description="Modal panel, show/hide based on modal state."
                     x-transition:enter="ease-out duration-300"
                     x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                     x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
                     x-transition:leave="ease-in duration-200"
                     x-transition:lea ve-start="opacity-100 translate-y-0 sm:scale-100"
                     x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                     class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-xl sm:w-full"
                     role="dialog"
                     aria-modal="true"
                     aria-labelledby="modal-headline">

                    <div class="bg-white px-4 pt-5 pb-4 sm:pb-4">
                        <div>
                            <form autocomplete="off" action="{{route('schedules.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="mt-3 mb-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                    <h3 class="text-lg text-center leading-6 font-medium text-gray-900">
                                        Create a Event
                                    </h3>

                                    {{-- create form --}}
                                    <label class="block p-2">
                                        <span class="text-gray-700 font-semibold text-sm">Schedules name</span>

                                        <input  class="text-gray-700 p-2 border rounded text-sm @error ('name') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
                                                placeholder="Enter hotel name.."
                                                name="name"
                                                required
                                                value = "{{old('name')}}"
                                        >
                                    </label>

                                    @error('name')
                                    <span class="text-red-500 text-xs">{{$message}}</span>
                                    @enderror

                                    <label class="block p-2">
                                        <span class="text-gray-700 text-sm">Select Event Status</span>
                                        <select name="status" class="text-gray-700 p-2 border text-sm @error ('status') border-red-500 @enderror form-input mt-1 rounded-lg block w-full">
                                            <option value="Active">Opened</option>
                                            <option value="Closed">Closed</option>
                                        </select>
                                    </label>

                                    <label class="block p-2">
                                        <span class="text-gray-700 font-semibold text-sm">Event Poster</span>

                                        <input  class="text-gray-700 p-2 border rounded text-sm @error ('image') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
                                                name="image"
                                                required
                                                type="file"
                                                value="{{ old('image') }}"
                                        >
                                    </label>

                                    @error('image')
                                    <span class="text-red-500 text-xs">{{$message}}</span>
                                    @enderror

                                    <x-input.group label="Starting date" for="starting" :error="$errors->first('starting')">
                                        <x-input.date value="{{old('starting')}}" name="starting" id="starting" placeholder="MM/DD/YYYY"/>
                                    </x-input.group>

                                    <x-input.group label="Due date" for="due" :error="$errors->first('due')">
                                        <x-input.date value="{{old('due')}}" name="due" id="due" placeholder="MM/DD/YYYY"/>
                                    </x-input.group>


                                    <label class="block p-2">
                                        <span class="text-gray-700 font-semibold text-sm">Description</span>
                                        <textarea class=" text-gray-700 p-2 border rounded text-sm @error ('description') border-red-500 @enderror  form-textarea rounded-lg mt-1 block w-full"
                                                  rows="3"
                                                  name="description"
                                                  placeholder="Enter some detail"
                                                  required
                                        >
                                {{old('description')}}
                            </textarea>

                                    </label>
                                    {{-- end create form --}}
                                </div>

                                <div class="px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                    <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
                        <button type="submit"
                                class="inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-blue-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-blue-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                           Create
                        </button>
                    </span>
                                    <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">

                        <a href="{{route('schedules.index')}}">
                            <button @click="open = false; setTimeout(() => open = true, 1000)" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                                Cancel
                            </button>
                        </a>
                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
</div>
</div>
@endsection

resources/views/themepark/schedule/edit.blade.php
@extends('layouts.app')

@section('content')
<div>
    <div class="bg-gray-300" style="height:auto;">

        <div x-data="{ open: true }" x-show="open" class="fixed bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
            <div x-show="open" x-description="Background overlay, show/hide based on modal state." x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" class="fixed inset-0 transition-opacity">
                <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <div x-show="open" x-description="Modal panel, show/hide based on modal state."
                 x-transition:enter="ease-out duration-300"
                 x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                 x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
                 x-transition:leave="ease-in duration-200"
                 x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
                 x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                 class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-xl sm:w-full"
                 role="dialog"
                 aria-modal="true"
                 aria-labelledby="modal-headline">

                <div class="bg-white px-4 pt-5 pb-4 sm:p-10 sm:pb-4">
                    <div>
                        <form autocomplete="off" action="{{route('schedules.update',$schedule->slug)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')

                            <div class="mt-3 mb-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                <h3 class="text-lg text-center leading-6 font-medium text-gray-900">
                                    Update a Event
                                </h3>

                                <label class="block p-2">
                                    <span class="text-gray-700 font-semibold text-sm">Event name</span>

                                    <input  class="text-gray-700 p-2 border rounded text-sm @error ('name') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
                                            placeholder="Enter hotel name.."
                                            name="name"
                                            required
                                            value = "{{$schedule->name}}"
                                    >
                                </label>

                                @error('name')
                                <span class="text-red-500 text-xs">{{$message}}</span>
                                @enderror

                                <label class="block p-2">
                                    <span class="text-gray-700 font-semibold text-sm">Event Poster</span>

                                    <input  class="text-gray-700 p-2 border rounded text-sm @error ('image') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
                                            name="image"
                                            type="file"
                                            value="{{old('image')}}}"
                                    >
                                </label>

                                <label class="block p-2">
                                    <span class="text-gray-700 text-sm">Select Event Status</span>
                                    <select name="status" class="text-gray-700 p-2 border text-sm @error ('status') border-red-500 @enderror form-input mt-1 rounded-lg block w-full">
                                        <option value="Active">Opened</option>
                                        <option value="Closed">Closed</option>
                                    </select>
                                </label>

                                @error('image')
                                <span class="text-red-500 text-xs">{{$message}}</span>
                                @enderror

                                <x-input.group label="Starting date" for="starting" :error="$errors->first('starting')">
                                    <x-input.date value="{{$schedule->starting}}" name="starting" id="starting" placeholder="MM/DD/YYYY"/>
                                </x-input.group>

                                <x-input.group label="Due date" for="due" :error="$errors->first('due')">
                                    <x-input.date value="{{$schedule->due}}" name="due" id="due" placeholder="MM/DD/YYYY"/>
                                </x-input.group>

                                <label class="block p-2">
                                    <span class="text-gray-700 font-semibold text-sm">Description</span>
                                    <textarea class=" text-gray-700 p-2 border rounded text-sm @error ('description') border-red-500 @enderror  form-textarea rounded-lg mt-1 block w-full"
                                              rows="3"
                                              name="description"
                                              placeholder="Enter some detail"
                                              required
                                    >
                                        {{$schedule->description}}
                                    </textarea>
                                </label>

                            </div>

                            <div class="px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                    <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
                            <button type="submit"
                                    class="inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-blue-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-blue-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                            Update
                        </button>
                    </span>
                                <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">
                        <a href="{{route('schedules.index')}}">
                            <button @click="open = false; setTimeout(() => open = true, 1000)" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                                Cancel
                            </button>
                        </a>
                    </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

@endsection

resources/views/themepark/schedule/form.blade.php
<label class="block p-2">
    <span class="text-gray-700 font-semibold text-sm">Schedules name</span>

    <input  class="text-gray-700 p-2 border rounded text-sm @error ('name') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
            placeholder="Enter hotel name.."
            name="name"
            required
            value = "{{old('name')}}"

    >
</label>

@error('name')
<span class="text-red-500 text-xs">{{$message}}</span>
@enderror

<label class="block p-2">
    <span class="text-gray-700 text-sm">Select Event Status</span>
    <select name="country_id" class="text-gray-700 p-2 border text-sm @error ('country_id') border-red-500 @enderror form-input mt-1 rounded-lg block w-full">
        <option value="Active">Opened</option>
        <option value="Closed">Closed</option>
    </select>
</label>

<label class="block p-2">
    <span class="text-gray-700 font-semibold text-sm">Event Poster</span>

    <input  class="text-gray-700 p-2 border rounded text-sm @error ('image') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
            name="image"
            type="file"
            value="{{old('image')}}}"
            @if($route!='schedules.edit')
            required
            value="{{old('image')}}}"
            @endif
    >
</label>

@error('image')
<span class="text-red-500 text-xs">{{$message}}</span>
@enderror

<x-input.group label="Starting date" for="starting" :error="$errors->first('starting')">
    <x-input.date value="{{old('starting')}}" name="starting" id="starting" placeholder="MM/DD/YYYY"/>
</x-input.group>

<x-input.group label="Due date" for="due" :error="$errors->first('due')">
    <x-input.date value="{{old('due')}}" name="due" id="due" placeholder="MM/DD/YYYY"/>
</x-input.group>


<label class="block p-2">
    <span class="text-gray-700 font-semibold text-sm">Description</span>
    <textarea class=" text-gray-700 p-2 border rounded text-sm @error ('description') border-red-500 @enderror  form-textarea rounded-lg mt-1 block w-full"
              rows="3"
              name="description"
              placeholder="Enter some detail"
              required
    >
            {{old('description')}}
        </textarea>

</label>

resources/views/themepark/schedule/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="border p-10">
        <div class="container mx-auto">

            <div class="text-left">
                <h2 class="font-bold p-2 capitalize border-b text-3xl">Schedule Events</h2>
            </div>

            <div class="flex m-2">

                <a href="{{ route('schedules.create') }}"
                  class="bg-green-400 px-3 py-1 mr-2 text-sm rounded hover:bg-green-500 hover:text-white">
                    Create
                </a>

            </div>

            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                    <table class="min-w-full ">
                        <thead>
                        <tr>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">#</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Name</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Status</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">starting</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">due_date</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Description</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Updated</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Action</th>

                        </tr>
                        </thead>
                        <tbody>
                        @forelse ($events as $event)

                            <tr class="border-b border-gray-200 bg-white text-sm text-gray-800">
                                <td class="border text-center "> {{$loop->iteration}}</td>
                                <td class="border text-center "> {{$event->name}}</td>
                                <td class="border text-center {{ $event->status == 'Closed'  ? 'text-red-800' : 'font-bold text-green-400'}}">
                                    {{$event->status}}
                                </td>
                                <td class="border text-center "> {{$event->starting->format('D, d-M ') }}</td>
                                <td class="border text-center "> {{$event->due->format('D, d-M ')  }}</td>
                                <td class="border text-center "> {{$event->description}}</td>
                                <td class="border text-center "> {{$event->updated_at->diffForHumans()}}</td>
                                <td class="border py-2">

                                    <div class="flex justify-center p-1">
                                        <a href="{{route('schedules.edit', $event->slug )}}"
                                           class="bg-orange-400 px-3 py-1 text-sm mr-2 rounded hover:bg-orange-500 hover:text-white">
                                            Edit
                                        </a>


                                        <x-modal title="confirmation">
                                            <x-slot name="trigger">
                                                <button class="bg-red-400 px-3 py-1 mr-2 text-sm rounded hover:bg-red-500 hover:text-white">
                                                    Delete
                                                </button>
                                            </x-slot>

                                            <span class="text-centre text-gray-700">Are you sure you want to delete this schedule? </span>

                                            <x-slot name="submit">
                                                <form action="{{route('schedules.destroy', $event->slug )}}" method="POST">
                                                    @method('DELETE')
                                                    @csrf

                                                    <button type="submit"
                                                            class=" text-sm bg-red-600 text-white hover:bg-red-400 p-2 rounded">
                                                        Delete
                                                    </button>

                                                </form>
                                            </x-slot>

                                            <x-slot name="clear">
                                                <a  @click="on = false"
                                                    class="inline-flex cursor-pointer justify-center w-full rounded-md border
                                                    border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700
                                                    shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue
                                                    transition ease-in-out duration-150 sm:text-sm sm:leading-5"
                                                >
                                                    Cancel
                                                </a>
                                            </x-slot>
                                        </x-modal>

                                    </div>
                                </td>
                            </tr>
                        @empty
                            <p class="text-center bg-red-500 text-white leading-5 p-2 border shadow-lg">
                                No schedule added!
                            </p>

                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/themepark/schedule/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="border p-20">

        <div class="container mx-auto">

        <div class="mt-10 m-3 mt-5">
        <h2 class="text-teal-600 text-2xl font-bold mb-1">
            It seems like you dont have a booking! for
            <span> {{ $event->first()->name ?? null }} </span>
        </h2>
            <p class="leading text-gray-500">No problem below find the available hotels</p>
        </div>

        <p class="leading flex border-b text-gray-800 font-medium mb-4 text-2xl p-2">
            Available Hotels
        </p>

        <div class="flex flex-wrap mb-10 justify-center">

            @foreach($hotels as $hotel)

                <div class="max-w-sm overflow-hidden shadow-lg border m-2 hover:shadow-xl rounded-lg  duration-300 transform bg-white rounded shadow-sm hover:-translate-y-1">
                    <img class="w-full object-cover" style="height:350px; width: 470px"
                         src="{{ $hotel->image() }}"
                         alt="">
                    <div class="px-6 py-4">
                        <div class="font-bold text-xl mb-2">
                            <a href="/set/{{$event->first()->slug}}/{{$hotel->slug}}"
                               class="capitalize hover:text-teal-500">
                                {{$hotel->name}}
                            </a>
                        </div>
                        <p class="text-gray-700 text-base">
                            {{$hotel->description}}
                        </p>
                    </div>
                </div>

            @endforeach

        </div>
        {{ $hotels->links() }}
    </div>
</div>

@endsection