routes/web.php
<?php

use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HotelController;
use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\RoomController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth()->login(
//    \App\Models\User::find(1)
//);

Route::group(['middleware' => 'auth'], function (){
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::resource('schedules', ScheduleController::class);
    Route::resource('bookings', BookingController::class);
    Route::resource('activities', ActivitiesController::class);
    Route::post('/{activity}/buy',[ActivitiesController::class,'purchaseTicket'])->name('buy.tickets');
    Route::get('themepark/activites',[PageController::class,'activities'])->name('themepark.activities');
    Route::get('user/history',[PageController::class, 'getUserHistory'])->name('user.history');
    Route::get('set/{schedule}/{hotel}',[PageController::class,'setScheduleRoom'])->name('set.schedule');
    Route::post('guest/{schedule}/{room}',[BookingController::class, 'guestBooking'])->name('confirm.create');
    Route::delete('tickets/{ticket}/{booking}',[TicketController::class, 'destroy'])->name('tickets.destroy');
});

Route::get('/',[PageController::class,'index'])->name('home');
Route::get('/home',[PageController::class,'index'])->name('home');
Route::get('/about',[PageController::class,'about'])->name('about');
Route::get('/themepark/hotels',[PageController::class,'hotel'])->name('themepark.hotels');

app/Models/Activity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Activity extends Model
{
    use HasFactory,SoftDeletes;
    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected $guarded = [];

    public function tickets(){
        return $this->hasMany(Ticket::class);
    }

}

app/Http/Controllers/ActivitiesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ActivityCreateRequest;
use App\Http\Requests\ActivityUpdateRequest;
use App\Models\Activity;
use App\Models\Booking;
use App\Models\Ticket;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ActivitiesController extends Controller
{

    public function index()
    {
        $activities = Activity::all();
        return view('themepark.activities.index',compact('activities'));
    }

    public function store(ActivityCreateRequest $request)
    {
        $data = [
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'price' => $request->price,
            'description' => $request->description,
        ];
        Activity::create($data);
        return redirect()->route('activities.index')
                         ->with('success','Activity created successfully.');
    }

    public function purchaseTicket(Activity $activity, Request $request )
    {
        $event = $request->event;
        $price = $activity->price;
        $no = $request->amount;
        //get the active bookings
        $bookings = Booking::with(['schedule'=>function($query){
            $query->where('status','Active');
        }])->where('schedule_id',$event)->get();

        //for schedule buy the same ticket
        foreach ($bookings as $booking){
            Ticket::create([
               'booking_id' => $booking->id,
               'activity_id' => $activity->id,
               'tickets' => $no,
            ]);

            //updated the booking total
            $booking->update([
                'total' => $booking->total + ( $price * $no ),
            ]);
        }
        return redirect()->route('user.history')
            ->with('success','Activity added to selected Event and Booking updated successfully.');
    }


    public function edit(Activity $activity)
    {
        return view('themepark.activities.edit',compact('activity'));
    }


    public function update(ActivityUpdateRequest $request, Activity $activity)
    {
        $data = [
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'price' => $request->price,
            'description' => $request->description,
        ];

        $activity->update($data);
        return redirect()->route('activities.index')
            ->with('success','Activity updated successfully.');
    }


    public function destroy(Activity $activity)
    {
        $activity->delete();
        return redirect()->route('activities.index')
             ->with('success','Activity deleted successfully.');
    }
}

resources/views/themepark/activities/edit.blade.php
@extends('layouts.app')

@section('content')
<div>
    <div class="bg-gray-300" style="height:auto;">

        <div x-data="{ open: true }" x-show="open" class="fixed bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
            <div x-show="open"
                 x-description="Background overlay, show/hide based on modal state."
                 x-transition:enter="ease-out duration-300"
                 x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100"
                 x-transition:leave="ease-in duration-200"
                 x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0"
                 class="fixed inset-0 transition-opacity">
                <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <div x-show="open" x-description="Modal panel, show/hide based on modal state."
                 x-transition:enter="ease-out duration-300"
                 x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                 x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
                 x-transition:leave="ease-in duration-200"
                 x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
                 x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                 class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-xl sm:w-full"
                 role="dialog"
                 aria-modal="true"
                 aria-labelledby="modal-headline">

                <div class="bg-white px-4 pt-5 pb-4 sm:p-10 sm:pb-4">
                    <div>
                        <form autocomplete="off" action="{{route('activities.update',$activity->slug)}}"
                              method="POST"
                              enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')

                            @include('themepark.activities.form')

                            <div class="px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                    <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
                            <button type="submit"
                                    class="inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-blue-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-blue-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                            Update
                        </button>
                    </span>
                                <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">
                        <a href="{{route('hotels.index')}}">
                            <button @click="open = false; setTimeout(() => open = true, 1000)" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                                Cancel
                            </button>
                        </a>
                    </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/themepark/activities/form.blade.php
@php
    $route = Route::currentRouteName();
@endphp

<label class="block p-2">
    <span class="text-gray-700 font-semibold text-sm">Activity name</span>
    <input  class="text-gray-700 p-2 border rounded text-sm @error ('name') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
            placeholder="Enter activity name.."
            name="name"
            required
            @if($route==='activities.edit')
            value = "{{ $activity->name }}"
            @else
            value = "{{old('name')}}"
            @endif
    >
</label>

@error('name')
<span class="text-red-500 text-xs">{{$message}}</span>
@enderror



<label class="block p-2">
    <span class="text-gray-700 font-semibold text-sm">Price</span>
    <input  class="text-gray-700 p-2 border rounded text-sm @error ('price') border-red-500 @enderror form-input mt-1 rounded-lg block w-full"
            placeholder="0.00 MVR"
            name="price"
            type="number"
            required
            @if($route==='activities.edit')
            value = "{{ $activity->price }}"
            @else
            value = "{{old('name')}}"
            @endif
    >
</label>

@error('price')
<span class="text-red-500 text-xs">{{$message}}</span>
@enderror


<label class="block p-2">
    <span class="text-gray-700 font-semibold text-sm">Description</span>
    <textarea class="text-gray-700 p-2 border rounded text-sm @error ('description') border-red-500 @enderror  form-textarea rounded-lg mt-1 block w-full"
              rows="3"
              name="description"
              placeholder="Enter some detail or rules"
              required
    >
         @if($route==='activities.edit')
            {{$activity->description}}
        @else
            {{old('description')}}
        @endif

        </textarea>
</label>

resources/views/themepark/activities/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="border">
        <div class="container mx-auto">

            <div class="text-left">
                <h2 class="font-bold p-2 capitalize border-b text-3xl">Activities</h2>
            </div>

            <div class="flex m-2">

                <x-modal title="Create a Room">
                    <x-slot name="trigger">
                        <button class="bg-green-400 px-3 py-1 mr-2 text-sm rounded hover:text-white hover:bg-green-500">
                            Create
                        </button>
                    </x-slot>

                    <form autocomplete="off" action="{{route('activities.store')}}"
                          method="POST"
                          enctype="multipart/form-data">
                        @csrf
                        @include('themepark.activities.form')

                        <button type="submit"
                                class=" text-sm bg-blue-600 mt-2 text-white hover:bg-blue-400 py-2 px-3 rounded">
                            Save
                        </button>

                    </form>

                    <x-slot name="submit">

                    </x-slot>


                    <x-slot name="clear">
                        <a  @click="on = false"
                            class="inline-flex cursor-pointer justify-center w-full rounded-md border px-4 py-2 bg-red-500 text-base
                            leading-6 font-medium text-gray-700 shadow-sm hover:text-white focus:outline-none focus:border-blue-300
                            focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5"
                        >
                            Cancel
                        </a>
                    </x-slot>

                </x-modal>

            </div>

            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                    <table class="min-w-full ">
                        <thead>
                        <tr>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">#</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Name</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Price</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Description</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Created_at</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Action</th>

                        </tr>
                        </thead>
                        <tbody>

                        @forelse ($activities as $activity)

                            <tr class="border-b border-gray-200 bg-white text-sm text-gray-800">
                                <td class="border text-center p-2"> {{$loop->iteration}}</td>
                                <td class="border text-center p-2"> {{$activity->name}}</td>
                                <td class="border text-center p-2"> {{$activity->price}}</td>
                                <td class="border text-center p-2"> {{$activity->description}}</td>
                                <td class="border text-center p-2"> {{$activity->created_at->diffForHumans()}}</td>
                                <td class="border text-center p-2">

                                    <div class="flex justify-center">
                                        <a href="{{ route('activities.edit', $activity->slug)}}"
                                           class="bg-indigo-400 px-3 py-1 mr-2 text-sm rounded hover:text-white hover:bg-indigo-700">
                                            Edit
                                        </a>

                                        <x-modal title="confirmation">

                                            <x-slot name="trigger">
                                                <button class="bg-red-400 px-3 py-1 mr-2 text-sm rounded hover:text-white hover:bg-red-500">
                                                    Delete
                                                </button>
                                            </x-slot>

                                            <span class="text-centre text-gray-500">Are you sure you want to delete this activity? </span>

                                            <x-slot name="submit">
                                                <form action="{{route('activities.destroy', $activity->slug )}}" method="POST">
                                                    @method('DELETE')
                                                    @csrf

                                                    <button type="submit"
                                                            class=" text-sm bg-red-600 text-white hover:bg-red-400 p-2 rounded">
                                                        Delete
                                                    </button>
                                                </form>
                                            </x-slot>

                                            <x-slot name="clear">
                                                <a  @click="on = false"
                                                    class="inline-flex cursor-pointer justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5"
                                                >
                                                    Cancel
                                                </a>
                                            </x-slot>
                                        </x-modal>

                                    </div>
                                </td>

                            </tr>
                        @empty
                            <p class="text-center bg-red-500 text-white leading-5 p-2 border shadow-lg">
                                No activities added!
                            </p>

                        @endforelse

                        </tbody>
                    </table>
                    <div class="px-5 py-5 bg-white border-t flex flex-col xs:flex-row items-center xs:justify-between">
                <span class="text-xs xs:text-sm text-gray-900">

                </span>
                        <div class="inline-flex mt-2 xs:mt-0">
                            {{-- {{$brands->links()}} --}}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection