routes/web.php
<?php

use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HotelController;
use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\RoomController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth()->login(
//    \App\Models\User::find(1)
//);

Route::group(['middleware' => 'auth'], function (){
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::resource('schedules', ScheduleController::class);
    Route::resource('bookings', BookingController::class);
    Route::resource('activities', ActivitiesController::class);
    Route::post('/{activity}/buy',[ActivitiesController::class,'purchaseTicket'])->name('buy.tickets');
    Route::get('themepark/activites',[PageController::class,'activities'])->name('themepark.activities');
    Route::get('user/history',[PageController::class, 'getUserHistory'])->name('user.history');
    Route::get('set/{schedule}/{hotel}',[PageController::class,'setScheduleRoom'])->name('set.schedule');
    Route::post('guest/{schedule}/{room}',[BookingController::class, 'guestBooking'])->name('confirm.create');
    Route::delete('tickets/{ticket}/{booking}',[TicketController::class, 'destroy'])->name('tickets.destroy');
});

Route::get('/',[PageController::class,'index'])->name('home');
Route::get('/home',[PageController::class,'index'])->name('home');
Route::get('/about',[PageController::class,'about'])->name('about');
Route::get('/themepark/hotels',[PageController::class,'hotel'])->name('themepark.hotels');

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Booking extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable = [
    'uuid',
    'user_id',
    'room_id',
    'schedule_id',
    'total',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    public function room(){
        return $this->belongsTo(Room::class);
    }

    public function schedule(){
        return $this->belongsTo(Schedule::class);
    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\BookingCreateRequest;
use App\Models\Booking;
use App\Models\Room;
use App\Models\Schedule;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class BookingController extends Controller
{

    public function index()
    {
        $bookings = Booking::with(['room','schedule'])->latest()->get();
        return view('themepark.booking.index',compact('bookings'));
    }

    public function create()
    {
        return view('themepark.booking.index');
    }

    public function bookingCreate(Room $room)
    {
        $events  = Schedule::where('status','Active')->get();
        return view('themepark.booking.create', compact('room','events'));
    }

    public function store(BookingCreateRequest $request)
    {

        $user = User::where('email', $request->email)->first();

        //create customer
        if (empty($user)){
            $user = User::create([
                'name'  => $request->name,
                'nic'  => $request->nic,
                'mobile'  => $request->mobile,
                'email' => $request->email,
                'isAdmin'=> 0,
                'password' => md5( Str::random(8))
            ]);
        }

        $room = Room::find($request->room);

        //create booking
        Booking::create([
            'uuid' => Str::random(4),
            'user_id' => $user->id,
            'schedule_id' => $request->event,
            'room_id' => $request->room,
            'total' => $room->price,
        ]);

        return redirect()->route('bookings.index')
                         ->with('success','Booked successfully.');
    }

    public function guestBooking(Schedule $schedule, Room $room){

        $user = Auth::user();
        Booking::create([
            'uuid' => Str::random(4),
            'user_id' => $user->id,
            'schedule_id' => $schedule->id,
            'room_id' => $room->id,
            'total' => $room->price,
        ]);
        return redirect()->route('user.history')
                ->with('success','Booked successfully.');
    }

    public function destroy(Booking $booking)
    {
        $booking->delete();
        return redirect()->route('bookings.index')
            ->with('success','Booking deleted successfully.');
    }
}

resources/views/themepark/booking/create.blade.php
@extends('layouts.app')

@section('content')


    <div class="h-screen w-full flex items-center justify-center bg-teal-lightest font-sans">
        <div class="h-screen w-full absolute flex items-center justify-center bg-modal">
            <div class="">
                <div class="mb-4">
                    <h1>Welcome!</h1>
                </div>
                <div class="">
                    <p>Ready to get started? Keep scrolling to see some great components.</p>
                </div>
                <div class="flex justify-center">
                    <button class="flex-no-shrink text-white py-2 px-4 rounded bg-teal hover:bg-teal-dark">Let's Go</button>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/themepark/booking/edit.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div class="bg-gray-300" style="height:auto;">

            <div x-data="{ open: true }" x-show="open" class="fixed bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
                <div x-show="open"
                     x-description="Background overlay, show/hide based on modal state."
                     x-transition:enter="ease-out duration-300"
                     x-transition:enter-start="opacity-0"
                     x-transition:enter-end="opacity-100"
                     x-transition:leave="ease-in duration-200"
                     x-transition:leave-start="opacity-100"
                     x-transition:leave-end="opacity-0"
                     class="fixed inset-0 transition-opacity">
                    <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
                </div>

                <div x-show="open" x-description="Modal panel, show/hide based on modal state."
                     x-transition:enter="ease-out duration-300"
                     x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                     x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
                     x-transition:leave="ease-in duration-200"
                     x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
                     x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                     class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-xl sm:w-full"
                     role="dialog"
                     aria-modal="true"
                     aria-labelledby="modal-headline">

                    <div class="bg-white px-4 pt-5 pb-4 sm:p-10 sm:pb-4">
                        <div>
                            <form autocomplete="off" action="{{route('hotels.update',$hotel->slug)}}"
                                  method="POST"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')

                                @include('themepark.booking.form')

                                <div class="px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                    <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
                            <button type="submit"
                                    class="inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-blue-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-blue-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                            Update
                        </button>
                    </span>
                                    <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">
                        <a href="{{route('hotels.index')}}">
                            <button @click="open = false; setTimeout(() => open = true, 1000)" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                                Cancel
                            </button>
                        </a>
                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

@endsection

resources/views/themepark/booking/form.blade.php
    <label class="block m-2">
        <span class="text-gray-700 font-semibold text-sm">Customer name</span>
        <input  class="text-gray-700  p-2 border rounded text-sm
            form-input mt-1 rounded-lg block w-full
            outline-none
            @error ('name') border-red-500 @enderror"
                placeholder="Enter Customer name.."
                name="name"
                required
        >

        @error('name')
        <span class="text-red-500 text-xs">{{$message}}</span>
        @enderror
    </label>

<label class="block m-2">
    <span class="text-gray-700 font-semibold text-sm">Email</span>
    <input  class="text-gray-700  p-2 border rounded text-sm
            form-input mt-1 rounded-lg block w-full
            outline-none
            @error ('email') border-red-500 @enderror"
            placeholder="Enter Customer email.."
            name="email"
            required
            value="{{old('email')}}"
    >

    @error('email')
    <span class="text-red-500 text-xs">{{$message}}</span>
    @enderror
</label>

    <label class="block m-2">
        <span class="text-gray-700 font-semibold text-sm">NIC(ex-A00123)</span>
        <input  class="text-gray-700 p-2 border rounded text-sm
            form-input mt-1 rounded-lg block w-full
            outline-none
            @error ('nic') border-red-500 @enderror"
                placeholder="Enter hotel name.."
                name="nic"
                required
                value="{{old('nic')}}"
        >

        @error('nic')
        <span class="text-red-500 text-xs">{{$message}}</span>
        @enderror
    </label>

    <label class="block m-2">
        <span class="text-gray-700 font-semibold text-sm">Mobile</span>
        <input  class="text-gray-700 p-2 border rounded text-sm
                form-input mt-1 rounded-lg block w-full
                outline-none
                @error ('name') border-red-500 @enderror"
                placeholder="mobile 7777070.."
                name="mobile"
                type="number"
                required
                value="{{old('number')}}"
        >

        @error('number')
        <span class="text-red-500 text-xs">{{$message}}</span>
        @enderror
    </label>

<livewire:event-room />

resources/views/themepark/booking/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="">
        <div x-data ="{open:false}" x-cloak class="container mx-auto p-2">
            <div class="text-left">
                <h2 class="font-bold capitalize border-b text-3xl">Bookings</h2>
            </div>
            <button @click="open = true" x-show="!open" class="bg-green-500 px-3 py-1 m-2
                    text-sm rounded hover:text-white hover:bg-green-400">
                New Booking
            </button>

            <div x-show="open" class="h-screen w-full flex flex-col items-center justify-center font-sans">
                <div class="w-full absolute flex items-center justify-center">
                    <div class="bg-white rounded-lg shadow-2xl border p-8 m-4 w-1/2 overflow-y-scroll">
                        <div class="mb-2">
                            <h1 class="font-medium text-2xl text-center">Make New Booking</h1>
                        </div>
                        <div class="mb-8">
                            <form autocomplete="off" action="{{ route('bookings.store') }}" method="POST">
                                @csrf
                                @include('themepark.booking.form')

                            <div class="mt-5 sm:px-6 sm:flex sm:flex-row-reverse">
                                <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
                                    <button type="submit"
                                    class="inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-blue-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-blue-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                                        Create
                                    </button>
                                </span>
                                <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">
                                    <a href="{{route('bookings.index')}}">
                                        <button @click="open = false; setTimeout(() => open = true, 1000)"
                                                type="submit"
                                                class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                                            Cancel
                                        </button>
                                    </a>
                                </span>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div x-show="!open"  class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                    <table class="min-w-full">
                        <thead>
                        <tr>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">#</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Room</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Room Type</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Schedule</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Total</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Created_at</th>
                            <th class="px-5 p-2 border-b-2 border-teal-400 bg-teal-300 text-center text-xs text-gray-800">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                            @forelse ($bookings as $booking)

                                <tr class="border-b border-gray-200 bg-white text-sm text-gray-800">
                                    <td class="border text-center p-2"> {{$loop->iteration}}</td>
                                    <td class="border text-center p-2"> {{$booking->room->name}}</td>
                                    <td class="border text-center p-2"> {{$booking->room->type}}</td>
                                    <td class="border text-center p-2"> {{$booking->schedule->starting->toDateString()}}</td>
                                    <td class="border text-center p-2"> {{number_format($booking->total,2)}}</td>
                                    <td class="border text-center p-2"> {{$booking->created_at->diffForHumans()}}</td>
                                    <td class="border text-center p-2">

                                        <div class="flex justify-center">

                                            <x-modal title="confirmation">

                                                <x-slot name="trigger">
                                                    <button class="bg-red-400 px-3 py-1 mr-2 text-sm rounded hover:text-white hover:bg-red-500">
                                                        Delete
                                                    </button>
                                                </x-slot>

                                                <span class="text-centre text-gray-500">Are you sure you want to delete this booking? </span>

                                                <x-slot name="submit">
                                                    <form action="{{route('bookings.destroy', $booking->id )}}" method="POST">
                                                        @method('DELETE')
                                                        @csrf

                                                        <button type="submit"
                                                                class=" text-sm bg-red-600 text-white hover:bg-red-400 p-2 rounded">
                                                            Delete
                                                        </button>
                                                    </form>
                                                </x-slot>

                                                <x-slot name="clear">
                                                    <a  @click="on = false"
                                                        class="inline-flex cursor-pointer justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5"
                                                    >
                                                        Cancel
                                                    </a>
                                                </x-slot>
                                            </x-modal>

                                        </div>
                                    </td>

                                </tr>
                            @empty
                                <p class="text-center bg-red-500 text-white leading-5 p-2 border shadow-lg">
                                    No bookings added!
                                </p>

                            @endforelse
                        </tbody>
                    </table>
                    <div class="px-5 py-5 bg-white border-t flex flex-col xs:flex-row items-center xs:justify-between">
                <span class="text-xs xs:text-sm text-gray-900">

                </span>
                        <div class="inline-flex mt-2 xs:mt-0">
                            {{-- {{$brands->links()}} --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection