routes/web.php
<?php

use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HotelController;
use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\RoomController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth()->login(
//    \App\Models\User::find(1)
//);

Route::group(['middleware' => 'auth'], function (){
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::resource('schedules', ScheduleController::class);
    Route::resource('bookings', BookingController::class);
    Route::resource('activities', ActivitiesController::class);
    Route::post('/{activity}/buy',[ActivitiesController::class,'purchaseTicket'])->name('buy.tickets');
    Route::get('themepark/activites',[PageController::class,'activities'])->name('themepark.activities');
    Route::get('user/history',[PageController::class, 'getUserHistory'])->name('user.history');
    Route::get('set/{schedule}/{hotel}',[PageController::class,'setScheduleRoom'])->name('set.schedule');
    Route::post('guest/{schedule}/{room}',[BookingController::class, 'guestBooking'])->name('confirm.create');
    Route::delete('tickets/{ticket}/{booking}',[TicketController::class, 'destroy'])->name('tickets.destroy');
});

Route::get('/',[PageController::class,'index'])->name('home');
Route::get('/home',[PageController::class,'index'])->name('home');
Route::get('/about',[PageController::class,'about'])->name('about');
Route::get('/themepark/hotels',[PageController::class,'hotel'])->name('themepark.hotels');

resources/views/layouts/app.blade.php
@extends('layouts.base')

@section('body')

     @yield('content')
         @if ($message = Session::get('success'))
             <div x-data="{ open : true }" x-show.transition="open" x-on:click="open = false" class="alert-toast  fixed bottom-0 right-0 m-8 w-5/6 md:w-full max-w-sm z-20" >
                 <input type="checkbox" class="hidden" id="footertoast">
                 <label class="close cursor-pointer p-4 flex items-start justify-between w-full bg-green-400 rounded shadow-lg text-sm text-white"
                        title="close"
                        for="footertoast">

                     {{$message}}

                     <svg x-on:click="open = false" class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                         <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z">
                         </path>
                     </svg>
                 </label>
             </div>
         @endif
@endsection

resources/views/layouts/auth.blade.php
@extends('layouts.base')

@section('body')
    <div class="flex flex-col justify-center min-h-screen py-12 bg-gray-50 sm:px-6 lg:px-8">
        @yield('content')
    </div>
@endsection

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        @hasSection('title')
            <title>@yield('title') - {{ config('app.name') }}</title>
        @else
            <title>{{ config('app.name') }}</title>
        @endif


        <style>
             [x-cloak] {
			    display: none;
		    }
        </style>

        <link rel="stylesheet" href="/css/app.css">
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
        <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
        @livewireStyles
         @bukStyles

<!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
    </head>

    <body class="mx-auto">

        @include('layouts.desktop')

        @yield('body')

        @livewireScripts
        @bukScripts

        <script src="/js/app.js"></script>
    </body>

    <footer class="">
        <div class="flex bg-gray-200 justify-center border p-10">
            <p class="text-sm text-gray-800">
                © Copyright 2020 Themepark Inc. All rights reserved.
            </p>
        </div>
    </footer>
</html>

resources/views/layouts/desktop.blade.php
<x-nav>
    {{-- navbar link --}}
    @guest
    <x-nav-link route="login">Login</x-nav-link>
    @endguest
    <x-nav-link route="about">About Us</x-nav-link>
    <x-nav-link route="home">Latest Events</x-nav-link>
    <x-nav-link route="themepark.activities">Activities</x-nav-link>
    <x-nav-link route="themepark.hotels">Available Hotels</x-nav-link>
    {{-- <x-nav-link route="home">Acount</x-nav-link> --}}

{{-- dropdown nav --}}
    @auth
        @if(Auth::user()->isAdmin)
        <x-dropdown trigger="ThemePark Management">
            <x-dropdown-link href="{{route('bookings.index')}}">Booking</x-dropdown-link>
            <x-dropdown-link href="{{route('schedules.index')}}">Schedule Events</x-dropdown-link>
            <x-dropdown-link href="{{route('hotels.index')}}">Hotel</x-dropdown-link>
            <x-dropdown-link href="{{route('rooms.index')}}">Room</x-dropdown-link>
            <x-dropdown-link href="{{route('activities.index')}}">Activities</x-dropdown-link>
        </x-dropdown>
        @endif
    @endauth
</x-nav>

resources/views/layouts/mobile.blade.php
<div class="px-2 pt-2 pb-3">
   
    <x-mobile-link route="home">Home</x-mobile-link>

    <x-mobile-dropdown trigger="Name">
        <x-mobile-dropdown-link hrf="/home">Home</x-mobile-dropdown-link>
        <x-mobile-dropdown-link hrf="/home">Home</x-mobile-dropdown-link>
        <x-mobile-dropdown-link hrf="/home">Home</x-mobile-dropdown-link>
        <x-mobile-dropdown-link hrf="/home">Home</x-mobile-dropdown-link>
        <x-mobile-dropdown-link hrf="/home">Home</x-mobile-dropdown-link>
    </x-mobile-dropdown>

</div>

resources/views/layouts/nav.blade.php
<div class="px-4 py-5 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
    <div class="relative flex grid items-center grid-cols-2 lg:grid-cols-3">
        <ul class="flex items-center hidden space-x-8 lg:flex">
            <li><a href="/" aria-label="Our product" title="Our product" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Product</a></li>
            <li><a href="/" aria-label="Our product" title="Our product" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Features</a></li>
            <li><a href="/" aria-label="Product pricing" title="Product pricing" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Pricing</a></li>
        </ul>
        <a href="/" aria-label="Company" title="Company" class="inline-flex items-center lg:mx-auto">
            <svg class="w-8 text-deep-purple-accent-400" viewBox="0 0 24 24" stroke-linejoin="round" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" stroke="currentColor" fill="none">
                <rect x="3" y="1" width="7" height="12"></rect>
                <rect x="3" y="17" width="7" height="6"></rect>
                <rect x="14" y="1" width="7" height="6"></rect>
                <rect x="14" y="11" width="7" height="12"></rect>
            </svg>
            <span class="ml-2 text-xl font-bold tracking-wide text-gray-800 uppercase">Company</span>
        </a>
        <ul class="flex items-center hidden ml-auto space-x-8 lg:flex">
            <li><a href="/" aria-label="Sign in" title="Sign in" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Sign in</a></li>
            <li>
                <a
                        href="/"
                        class="inline-flex items-center justify-center h-12 px-6 font-medium tracking-wide text-white transition duration-200 rounded shadow-md bg-deep-purple-accent-400 hover:bg-deep-purple-accent-700 focus:shadow-outline focus:outline-none"
                        aria-label="Sign up"
                        title="Sign up"
                >
                    Sign up
                </a>
            </li>
        </ul>
        <!-- Mobile menu -->
        <div class="ml-auto lg:hidden">
            <button aria-label="Open Menu" title="Open Menu" class="p-2 -mr-1 transition duration-200 rounded focus:outline-none focus:shadow-outline hover:bg-deep-purple-50 focus:bg-deep-purple-50">
                <svg class="w-5 text-gray-600" viewBox="0 0 24 24">
                    <path fill="currentColor" d="M23,13H1c-0.6,0-1-0.4-1-1s0.4-1,1-1h22c0.6,0,1,0.4,1,1S23.6,13,23,13z"></path>
                    <path fill="currentColor" d="M23,6H1C0.4,6,0,5.6,0,5s0.4-1,1-1h22c0.6,0,1,0.4,1,1S23.6,6,23,6z"></path>
                    <path fill="currentColor" d="M23,20H1c-0.6,0-1-0.4-1-1s0.4-1,1-1h22c0.6,0,1,0.4,1,1S23.6,20,23,20z"></path>
                </svg>
            </button>
            <!-- Mobile menu dropdown
            <div class="absolute top-0 left-0 w-full">
              <div class="p-5 bg-white border rounded shadow-sm">
                <div class="flex items-center justify-between mb-4">
                  <div>
                    <a href="/" aria-label="Company" title="Company" class="inline-flex items-center">
                      <svg class="w-8 text-deep-purple-accent-400" viewBox="0 0 24 24" stroke-linejoin="round" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" stroke="currentColor" fill="none">
                        <rect x="3" y="1" width="7" height="12"></rect>
                        <rect x="3" y="17" width="7" height="6"></rect>
                        <rect x="14" y="1" width="7" height="6"></rect>
                        <rect x="14" y="11" width="7" height="12"></rect>
                      </svg>
                      <span class="ml-2 text-xl font-bold tracking-wide text-gray-800 uppercase">Company</span>
                    </a>
                  </div>
                  <div>
                    <button aria-label="Close Menu" title="Close Menu" class="p-2 -mt-2 -mr-2 transition duration-200 rounded hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
                      <svg class="w-5 text-gray-600" viewBox="0 0 24 24">
                        <path
                          fill="currentColor"
                          d="M19.7,4.3c-0.4-0.4-1-0.4-1.4,0L12,10.6L5.7,4.3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l6.3,6.3l-6.3,6.3 c-0.4,0.4-0.4,1,0,1.4C4.5,19.9,4.7,20,5,20s0.5-0.1,0.7-0.3l6.3-6.3l6.3,6.3c0.2,0.2,0.5,0.3,0.7,0.3s0.5-0.1,0.7-0.3 c0.4-0.4,0.4-1,0-1.4L13.4,12l6.3-6.3C20.1,5.3,20.1,4.7,19.7,4.3z"
                        ></path>
                      </svg>
                    </button>
                  </div>
                </div>
                <nav>
                  <ul class="space-y-4">
                    <li><a href="/" aria-label="Our product" title="Our product" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Product</a></li>
                    <li><a href="/" aria-label="Our product" title="Our product" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Features</a></li>
                    <li><a href="/" aria-label="Product pricing" title="Product pricing" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Pricing</a></li>
                    <li><a href="/" aria-label="Sign in" title="Sign in" class="font-medium tracking-wide text-gray-700 transition-colors duration-200 hover:text-deep-purple-accent-400">Sign in</a></li>
                    <li>
                      <a
                        href="/"
                        class="inline-flex items-center justify-center w-full h-12 px-6 font-medium tracking-wide text-white transition duration-200 rounded shadow-md bg-deep-purple-accent-400 hover:bg-deep-purple-accent-700 focus:shadow-outline focus:outline-none"
                        aria-label="Sign up"
                        title="Sign up"
                      >
                        Sign up
                      </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
            -->
        </div>
    </div>
</div>